services:
  springboot:
    build: .
    image: pt
    container_name: pt
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - funfit

  mysql:
    image: mysql
    container_name: pt_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DATASOURCE_PASSWORD}
      MYSQL_DATABASE: pt
      MYSQL_PASSWORD: ${DATASOURCE_PASSWORD}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - funfit

  redis-master:
    image: bitnami/redis
    container_name: pt_redis_1
    hostname: pt_redis_1
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=1234
      - REDIS_MASTER_PASSWORD=1234
    ports:
      - "6379:6379"
    networks:
      - funfit

  redis-slave:
    image: bitnami/redis
    container_name: pt_redis_2
    hostname: pt_redis_2
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=pt_redis_1
      - REDIS_PASSWORD=1234
      - REDIS_MASTER_PASSWORD=1234
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    networks:
      - funfit

  redis-sentinel-1:
    image: bitnami/redis-sentinel
    container_name: pt_redis_sentinel_1
    hostname: pt_redis_sentinel_1
    environment:
      - REDIS_MASTER_HOST=pt_redis_1
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_PASSWORD=1234
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - "26379:26379"
    networks:
      - funfit

  redis-sentinel-2:
    image: bitnami/redis-sentinel
    container_name: pt_redis_sentinel_2
    hostname: pt_redis_sentinel_2
    environment:
      - REDIS_MASTER_HOST=pt_redis_1
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_PASSWORD=1234
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - "26380:26379"
    networks:
      - funfit

  redis-sentinel-3:
    image: bitnami/redis-sentinel
    container_name: pt_redis_sentinel_3
    hostname: pt_redis_sentinel_3
    environment:
      - REDIS_MASTER_HOST=pt_redis_1
      - REDIS_MASTER_SET=mymaster
      - REDIS_MASTER_PASSWORD=1234
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave
    ports:
      - "26381:26379"
    networks:
      - funfit

networks:
  funfit:
    external: true
